qs_school_ranking = {
    1: "Massachusetts Institute of Technology (MIT)",
    2: "Imperial College London",
    3: "University of Oxford",
    4: "Harvard University",
    5: "University of Cambridge",
    6: "Stanford University",
    7: "ETH Zurich - Swiss Federal Institute of Technology",
    8: "National University of Singapore (NUS)",
    9: "University College London",
    10: "California Institute of Technology (Caltech)",
    11: "University of Pennsylvania",
    12: "University of California, Berkeley (UCB)",
    13: "The University of Melbourne",
    14: "Peking University",
    15: "Nanyang Technological University, Singapore (NTU)",
    16: "Cornell University",
    17: "The University of Hong Kong",
    18: "The University of Sydney",
    19: "The University of New South Wales (UNSW Sydney)",
    20: "Tsinghua University",
    21: "University of Chicago",
    22: "Princeton University",
    23: "Yale University",
    24: "Université Paris Sciences et Lettres (PSL)",
    25: "University of Toronto",
    26: "École Polytechnique Fédérale de Lausanne (EPFL)",
    27: "The University of Edinburgh",
    28: "Technical University of Munich",
    29: "McGill University",
    30: "The Australian National University",
    31: "Seoul National University",
    32: "Johns Hopkins University",
    32: "The University of Tokyo",
    34: "Columbia University",
    34: "The University of Manchester",
    36: "The Chinese University of Hong Kong (CUHK)",
    37: "Monash University",
    38: "University of British Columbia",
    39: "Fudan University",
    40: "King's College London",
    40: "The University of Queensland",
    42: "University of California, Los Angeles (UCLA)",
    43: "New York University (NYU)",
    44: "University of Michigan-Ann Arbor",
    45: "Shanghai Jiao Tong University",
    46: "Institut Polytechnique de Paris",
    47: "The Hong Kong University of Science and Technology",
    47: "Zhejiang University",
    49: "Delft University of Technology",
    50: "Kyoto University",
    50: "Northwestern University",
    50: "London School of Economics and Political Science (LSE)",
    53: "Korea Advanced Institute of Science & Technology (KAIST)",
    54: "University of Bristol",
    55: "University of Amsterdam",
    56: "Yonsei University",
    57: "The Hong Kong Polytechnic University",
    58: "Carnegie Mellon University",
    59: "Ludwig Maximilian University of Munich",
    60: "University of Malaya (UM)",
    61: "Duke University",
    62: "City University of Hong Kong",
    63: "KU Leuven",
    63: "Sorbonne University",
    65: "The University of Auckland",
    66: "University of Texas at Austin",
    67: "Korea University",
    68: "National Taiwan University (NTU)",
    69: "The University of Warwick",
    69: "University of Illinois at Urbana-Champaign",
    71: "University of Buenos Aires (UBA)",
    72: "University of California, San Diego (UCSD)",
    73: "Université Paris-Saclay",
    74: "KTH Royal Institute of Technology",
    75: "Lund University",
    76: "University of Washington",
    77: "The University of Western Australia",
    78: "University of Glasgow",
    79: "Brown University",
    80: "University of Birmingham",
    80: "University of Southampton",
    82: "The University of Adelaide",
    82: "University of Leeds",
    84: "Heidelberg University",
    84: "Tokyo Institute of Technology (Tokyo Tech)",
    86: "Osaka University",
    87: "Trinity College Dublin, The University of Dublin",
    88: "University of Technology Sydney",
    89: "Durham University",
    89: "Pennsylvania State University",
    89: "Purdue University",
    92: "University of São Paulo",
    93: "Pontifical Catholic University of Chile (UC)",
    94: "Lomonosov Moscow State University",
    94: "National Autonomous University of Mexico (UNAM)",
    96: "University of Alberta",
    97: "Free University of Berlin",
    98: "Pohang University of Science and Technology (POSTECH)",
    99: "RWTH Aachen University",
    100: "University of Copenhagen"
}

usnews_school_ranking = {
    1: "Princeton University",
    2: "Massachusetts Institute of Technology",
    3: "Harvard University",
    4: "Stanford University",
    5: "Yale University",
    6: "California Institute of Technology",
    6: "Duke University",
    6: "Johns Hopkins University",
    6: "Northwestern University",
    10: "University of Pennsylvania",
    11: "Cornell University",
    11: "University of Chicago",
    13: "Brown University",
    13: "Columbia University",
    15: "Dartmouth College",
    15: "University of California--Los Angeles",
    17: "University of California, Berkeley",
    18: "Rice University",
    18: "University of Notre Dame",
    18: "Vanderbilt University",
    21: "Carnegie Mellon University",
    21: "University of Michigan--Ann Arbor",
    21: "Washington University in St. Louis",
    24: "Emory University",
    24: "Georgetown University",
    24: "University of Virginia",
    27: "University of North Carolina--Chapel Hill",
    27: "University of Southern California",
    29: "University of California, San Diego",
    30: "New York University",
    30: "University of Florida",
    30: "The University of Texas--Austin",
    33: "Georgia Institute of Technology",
    33: "University of California, Davis",
    33: "University of California--Irvine",
    33: "University of Illinois Urbana-Champaign",
    37: "Boston College",
    37: "Tufts University",
    39: "University of California, Santa Barbara",
    39: "University of Wisconsin--Madison",
    41: "Boston University",
    41: "The Ohio State University",
    41: "Rutgers University--New Brunswick",
    44: "University of Maryland, College Park",
    44: "University of Rochester",
    46: "Lehigh University",
    46: "Purdue University--Main Campus",
    46: "University of Georgia",
    46: "University of Washington",
    46: "Wake Forest University",
    51: "Case Western Reserve University",
    51: "Texas A&M University",
    51: "Virginia Tech",
    54: "Florida State University",
    54: "Northeastern University",
    54: "University of Minnesota--Twin Cities",
    54: "William & Mary",
    58: "North Carolina State University",
    58: "Stony Brook University--SUNY",
    58: "University of California, Merced",
    58: "University of Massachusetts--Amherst",
    58: "Villanova University",
    63: "Brandeis University",
    63: "George Washington University",
    63: "Michigan State University",
    63: "The Pennsylvania State University--University Park",
    63: "Santa Clara University",
    63: "Tulane University",
    63: "University of Miami",
    70: "Rensselaer Polytechnic Institute",
    70: "University of Connecticut",
    70: "University of Pittsburgh",
    73: "Binghamton University--SUNY",
    73: "Indiana University--Bloomington",
    73: "Syracuse University",
    76: "Colorado School of Mines",
    76: "Stevens Institute of Technology",
    76: "University at Buffalo--SUNY",
    76: "University of California, Riverside",
    80: "Clemson University",
    80: "Pepperdine University",
    80: "Rutgers University--Newark",
    80: "University of Illinois--Chicago",
    84: "New Jersey Institute of Technology",
    84: "University of California, Santa Cruz",
    86: "Drexel University",
    86: "Howard University",
    86: "Marquette University",
    86: "University of Delaware",
    86: "Worcester Polytechnic Institute",
    91: "American University",
    91: "Baylor University",
    91: "Fordham University",
    91: "Loyola Marymount University",
    91: "Rochester Institute of Technology",
    91: "Southern Methodist University",
    91: "University of South Florida",
    98: "Florida International University",
    98: "Gonzaga University",
    98: "Rutgers University--Camden",
    98: "Temple University",
    98: "University of Colorado Boulder",
    98: "University of Iowa",
    98: "Yeshiva University"
}